# -*- coding: utf-8 -*-
"""Quiz6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hyaEC5NRSB93ihC9CdYn5bTNG3ShOK6
"""

morsecode = {'A':'.-', 'B':'-...', 'C':'-.-.', 'D':'-..', 'E':'.', 'F':'..-.', 'G':'--.', 'H':'....', 'I':'..', 
         'J':'.---', 'K':'-.-', 'L':'.-..', 'M':'--', 'N':'-.', 'O':'---', 'P':'.--.', 'Q':'--.-', 'R':'.-.', 
         'S':'...', 'T':'-', 'U':'..-','V':'...-', 'W':'.--', 'X':'-..-', 'Y':'-.--', 'Z':'--..','1':'.----', 
         '2':'..---', '3':'...--', '4':'....-', '5':'.....', '6':'-....', '7':'--...', '8':'---..', '9':'----.', '0':'-----'}

words=input("Please enter word: ")
morseword=""
for c in words:
  C=c.upper()
  morseword=morseword + " " + morsecode[C]

print("morse code is",morseword)